### ISSUE TITLE
events.block.hits should only trigger on sword hits

### ISSUE THREAD

**Issue by kbsriram** [kbsriram/mcpiapi#1]
Via @arpruss
https://groups.google.com/d/msg/adventures-in-minecraft-forum/chq0v6Ka1zA/9UpH_VanFAAJ

Another thing is that it looks to me (I could be wrong) like your implementation of events.block.hits() returns all block hits, while according to the API as documented on stuffaboutcode and according to the Raspberry Juice source code, only sword hits should count.

I've added an events.setting(restrict_to_sword,x) option, default true, to control this, when it's true I check for sword wielding using:

```
private boolean holdingSword() { 
  ItemStack item = Minecraft.getMinecraft().thePlayer.getHeldItem(); 
  if (item != null) {
    String name = item.getUnlocalizedName();
    if (name != null)
      return name.contains("item.sword");
  } 
  return false;
} 
```

**Comment by arpruss** [comment]
I didn't know there was a SwordItem type to check for being an instance of. I'll try to remember to do it the same way.

Should we merge our projects? We are working against different MC versions, though, so I don't know how easy that would be. Might be better to just update in tandem at this point. We have different approaches, and we may eventually want to see which one is more efficient.

I am thinking of teaching a summer coding class for middle-schoolers based around this.

**Comment by kbsriram** [comment]
It'd be simpler for people to just go to one place for a forge mod for sure; so I'm in general agreement with all your points. How do you feel about continuing to keep in sync with any new commands we end up adding? I just mean, that if we add a new command, that it's not also exposed in a slightly different way in the other mod? I'm keeping an occasional eye on @martinohanlon 's changes as well for the same purpose.
